### ISSUE TITLE
Fix email capabilities

### ISSUE THREAD

**Issue by joelhulen** [HTBox/htbox-website#5] opened 2020-04-01 02:50 UTC
@tonysurma Richard reached out to me to help fix the email capabilities of this site. I'd like to coordinate with you to gain access to what I need so I can address these issues.

**Comment by tonysurma** [comment] 2020-04-02 20:47
Hello @joelhulen - Thanks for helping.  The issue is pretty straight forward, the fix is hopefully as well.  This codebase hasn't been touched in 7 years so I expect the API/library used to subscribe to the mailchimp list is likely out of date.  The code is [here](https://github.com/HTBox/htbox-website/blob/master/src/htbox/Controllers/MailingListController.cs#L44).

The runtime details of the error is method call failed - after digging nothing specific so again am assuming just a failed API call that no longer exists or similar.

While we have a specific 'secret' api key & list id but the code can/should be able to be tested/rewritten with those items from a free account if I recall correctly.

Thanks again

**Comment by tonysurma** [comment] 2020-04-17 14:26
closed in merged PRs today

**Closed by tonysurma** 2020-04-17 14:26 UTC
